### ISSUE TITLE
Main deck screen useless widget

### ISSUE THREAD

**Issue by nostachio** [nostachio/gloomdeck#13]
In the kv file, there's an image:
```
    Image:
        source: 'images/null.png'
        size_hint_x: .001
        size_hint_y: .001
```
It's just being used to keep indexes correct for updating widgets.  Can either find a better way to reference the widgets or adjust the indices.
